In [1]:
# sorting of the complete rows of an array based on the first column elements
# Hint: can use np.argsort() and slicing based indexing

In [48]:
import numpy as np
x=np.array([[5,6,2,7],[1,7,3,8],[2,5,8,9],[0,5,7,6]])

In [50]:
x

array([[5, 6, 2, 7],
       [1, 7, 3, 8],
       [2, 5, 8, 9],
       [0, 5, 7, 6]])

In [51]:
# first column elements using indexing based slicing
x[:,0]

array([5, 1, 2, 0])

In [52]:
# sorted indexes based on first column elements
np.argsort(x[:,0])

array([3, 1, 2, 0], dtype=int64)

In [53]:
# sorted array based on the requirement
x[np.argsort(x[:,0])]

array([[0, 5, 7, 6],
       [1, 7, 3, 8],
       [2, 5, 8, 9],
       [5, 6, 2, 7]])