### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [5]:
import numpy as np
x=np.array([[3.0,2.0,0,1.0],[10.0,12.0,10.0,9.0],[5.0,0,1.0,0]])
x[0,2]=np.nan
x[2,1]=np.nan
x[2,3]=np.nan
print("Original array:",x,sep="\n")
print("Find the missing data of the said array:",np.isnan(x),sep="\n")

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
### code here

In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [21]:
x=np.random.rand(2,3)
y=np.random.rand(2,3)
print("Checking if 2 arrays are equal element wise:",x==y,sep="\n")

Checking if 2 arrays are equal element wise:
[[False False False]
 [False False False]]


In [ ]:
### code here 

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [55]:
x=np.arange(0,16, dtype='int').reshape(4,4)
print("Original array:",x,sep="\n")
print("\nNew array after swapping first and last rows of the said array:")
y=x[0:1,0:].copy()
x[0:1,0:]=x[3:,0:]
x[3:,0:]=y
print(x)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
## code here

In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [6]:
l=[1,2,3,4,5]
a=np.array(l)
print("Converting list to array:",a,sep="\n")
t=([1,2,3],[4,5,6])
b=np.array(t)
print("Converting tuple to array:",b,sep="\n")


Converting list to array:
[1 2 3 4 5]
Converting tuple to array:
[[1 2 3]
 [4 5 6]]


In [ ]:
#### code here

###### 5. Write a NumPy program to find common values between two arrays.

In [71]:
x=np.arange(30,50,step=2)
print("First array:",x)
y=np.arange(40,51)
print("Second array:",y)
print("Common values between two arrays:",np.intersect1d(x,y),sep="\n")

First array: [30 32 34 36 38 40 42 44 46 48]
Second array: [40 41 42 43 44 45 46 47 48 49 50]
Common values between two arrays:
[40 42 44 46 48]


In [ ]:
### code here

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [26]:
x=np.arange(1,7).reshape(3,2)
print("Reshape 3x2:",x,sep="\n")
print("Reshape 2x3:",x.reshape(2,3),sep="\n")

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### code here

In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [8]:
x=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:",x,sep="\n")
y,z=np.unique(x,return_counts=True)
print("Frequency of unique values of the said array:",np.array((y,z)),sep="\n")

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
### code here

In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [85]:
x=np.array([[0,0,0],[1,2,3],[4,5,6]])
y=np.array([10,11,12])
print("Original arrays:","Array-1",x,"Array-2",y,sep="\n")
print("\nNew Array:",x+y,sep="\n")

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
### code here

In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [4]:
##### extracted data needs to be single dimension
x=np.arange(0,16).reshape((4, 4))
print("Original array:",x,sep="\n")
y=x[[1,1,1,1],[0,1,2,3]]
print("\nExtracted data: Second row",y,sep="\n")

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


In [ ]:
### code here

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [103]:
x=np.arange(0,16).reshape(4,4)
print("Original array:",x,sep="\n")
print("\nExtracted data: Third and fourth elements of the first and second rows",x[0:2,2:],sep="\n")

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## code here

In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [18]:
##### not taught in class
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday: ",yesterday)
today=np.datetime64('today','D')
print("Today: ",today)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2022-12-21
Today:  2022-12-22
Tomorrow:  2022-12-23


In [ ]:
### code here

###### 12. Write a NumPy program to find the first Monday in May 2017.

In [26]:
###### not taught in class
print("First Monday in May 2017:",np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'),sep="\n")

First Monday in May 2017:
2017-05-01


In [ ]:
## code here

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
